### PR TITLE
Support more dot marker types.

### PR DESCRIPTION
**Pull request by rhcad**
Add a callback parameter for plotPoints, thus we can draw small box, star and other marker via plotPoints.

I think Saltire class' scalability can be better, so I add a new class MarkerDrawable as substitute to support more dot marker types.

### CODE REVIEW

**Comment by schwa** [comment]
Added notes inline.

**Comment by rhcad** [comment]
Your 'Line' may be 'GuildLine' which is always vertical? I suppose 'Beeline' structure should be added to draw infinite line and used to calculate intersection with line and curcle.

**Comment by rhcad** [comment]
Would you link to add 'Beeline' structure which has init(start, end), init(x) and init(y) constructors?

**Comment by rhcad** [comment]
Can I ask a question about Pathable? I can't found a function of getting path of bezier segments, so I implement it in my project(https://github.com/rhcad/ShapeAnimation-Swift/blob/develop/ShapeAnimation_UITest/EllipseViewController.swift). Is there a convenient way instead of it?

Thanks!
Zhang Yungui

**Comment by schwa** [comment]
I'm not entirely sure what your definition of a "beeline" is. Can you define it better - perhaps point to some resources?

**Comment by schwa** [comment]
Pathable is a placeholder - the intent is to have it work like Drawable. You can extend an object for Pathable and it should be able to return a CGPath (or maybe a Path).

Currently it isn't implemented. Perhaps it should be removed and converted into a Github Ticket.

**Comment by rhcad** [comment]
This PR is may not necessary, so close it.

**Pull request closed without merging**
